# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/hello-world',
                'doc_host': 'https://phbui.github.io',
                'git_url': 'https://github.com/phbui/hello-world',
                'lib_path': 'hello_world'},
  'syms': {'hello_world.core': {'hello_world.core.foo': ('core.html#foo', 'hello_world/core.py')}}}
